# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeej',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'aeej',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprendizagens',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'aprendizagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AprendizagensAeej',
            fields=[
                ('tipo_operacao', models.CharField(blank=True, max_length=1, null=True)),
                ('descritor_operacao', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_padrao', models.IntegerField(blank=True, null=True)),
                ('contribuicao_do_aeej_na_aprendizagem', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aprendizagens_aeej',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AprendizagensDadosmultimodais',
            fields=[
                ('tipo_operacao', models.CharField(blank=True, max_length=1, null=True)),
                ('descritor_operacao', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aprendizagens_dadosmultimodais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('valor_maximo_pontos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenciasAprendizagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuicao_da_apredizagem_na_competencia', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'competencias_aprendizagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DadosMultimodais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dados_multimodais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivosCaptura',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dispositivos_captura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapasJogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'etapas_jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FasesJogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fases_jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_desde_quando_joga', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jogadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JogosDigitais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'jogos_digitais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NiveisDeApredizagem',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fim_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('jogadores_nesse_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'niveis_de_apredizagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NiveisDeCompetenciaAvaliacao',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fim_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('jogadores_nesse_nivel', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'niveis_de_competencia_avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NiveisJogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'niveis_jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'unidades_medida',
                'managed': False,
            },
        ),
    ]
